kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-fee-calculator-production-admin
  namespace: laa-fee-calculator-production
subjects:
  - kind: Group
    name: "github:apply-for-legalaid"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io