version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - "apt update"
       - "apt install -y awscli"
       #- "apt install -y git-crypt"
       - "wget https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64"
       - "chmod +x kops-linux-amd64"
       - "mv kops-linux-amd64 /usr/local/bin/kops"
       - "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
       - "chmod +x kubectl"
       - "mv ./kubectl /usr/local/bin/kubectl"
  pre_build:
    commands:
      - "mkdir ~/.kube/"
      - "cp ./kube/config ~/.kube/config"
  build:
    commands:
      - "kubectl config get-contexts"
      - "kubectl cluster-info"
      - "kubectl --context kuberos get namespaces"
      - "kubectl get pods --all-namespaces"
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
