version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - "sudo apt update"
       - "sudo apt install -y awscli"
       - "sudo snap install kubectl --classic"
       - "wget https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64"
       - "chmod +x kops-linux-amd64"
       - "mv kops-linux-amd64 /usr/local/bin/kops"
       - "snap install kubectl --classic"
       - "apt-get install git-crypt"
  pre_build:
    commands
      - "mkdir ~/.kube/"
      - "cp ./kube/config ~/.kube/config"
  build:
    commands:
      - "kubectl config get-contexts"
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
