version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"

phases:
  install:
    commands:
       - "apt update"
       - "apt install -y awscli git"
       - "wget https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64"
       - "chmod +x kops-linux-amd64"
       - "mv kops-linux-amd64 /usr/local/bin/kops"
       - "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
       - "chmod +x kubectl"
       - "mv ./kubectl /usr/local/bin/kubectl"
       - "git clone https://github.com/AGWA/git-crypt.git"
       - "cd git-crypt; make; make install PREFIX=/usr/local; cd -"
  pre_build:
    commands:
      - "mkdir ~/.kube/"
      - "cp ./kube/config ~/.kube/config"
      - "export KOPS_STATE_STORE=s3://moj-cp-k8s-investigation-kops"
      - "kops export kubecfg non-production.k8s.integration.dsd.io"
  build:
    commands:
      - "kubectl config get-contexts"
      - "kubectl cluster-info"
      - "kubectl get namespaces"
      - "kubectl get pods --all-namespaces"
      - "ls namespaces/ | while read file; do kubectl create -f namespaces/$file/namespace.yaml; kubectl apply -f namespaces/$file --namespace=$file; done"
#     - "kubectl delete namespaces dev"

  #post_build:
    #commands:
      # - command

#artifacts:
  #files:
    # - location
  #discard-paths: yes
  #base-directory: location

#cache:
  #paths:
    # - paths
