apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: logging
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 8Gi
    limits.cpu: 12000m
    limits.memory: 12Gi
