apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: c100-application-staging
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
