kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moj-s3-virus-scan-dev-admin
  namespace: moj-s3-virus-scan-dev
subjects:
  - kind: Group
    name: "github:correspondence"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
