apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: concourse
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: concourse-tiller-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: concourse
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
