apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: formbuilder-services-staging
spec:
  limits:
  - default:
      cpu: 30m
      memory: 300Mi
    defaultRequest:
      cpu: 30m
      memory: 128Mi
    type: Container
