kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moving-people-safely-staging-admin
  namespace: moving-people-safely-staging
subjects:
  - kind: Group
    name: "github:moving-people-safely-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
