apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: 8000m
    requests.memory: 16Gi
    limits.cpu: 12000m
    limits.memory: 24Gi
