apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: cp-reference-app
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: cp-reference-app
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: cp-reference-app
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
