apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: test-pr-56
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: test-pr-56
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: test-pr-56
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
