apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: test-pr-56

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: test-pr-56
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "create"
      - "delete"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
    verbs:
      - "create"
      - "delete"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: test-pr-56
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: test-pr-56
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
