apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: "1"
        memory: "200m"
      requests:
        cpu: "1" 
        memory: "100m"
    ports:
    - containerPort: 80
