kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: andalusia-dev-admin
  namespace: andalusia-dev
subjects:
  - kind: Group
    name: "github:andalusia"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
