apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: abdi-sample-app-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: abdi-sample-app-dev
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: abdi-sample-app-dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io