kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prisoner-categorisation-tool-dev-admin
  namespace: prisoner-categorisation-tool-dev
subjects:
  - kind: Group
    name: "github:prisoner-categorisation-tool"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
