# Bind admin role for namespace to team group & publisher ServiceAccount
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-services-staging-admins
  namespace: formbuilder-services-staging
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: formbuilder-publisher-workers-dev
    namespace: formbuilder-platform-dev
  - kind: ServiceAccount
    name: formbuilder-publisher-workers-staging
    namespace: formbuilder-platform-staging
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
