apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
        