kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cica-development-admin
  namespace: cica-development
subjects:
  - kind: Group
    name: "github:CICA"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
